// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01oo8mx5XLvyad0ai31empmtDddBHFNg',
    appId: '1:886098407421:web:cfaf8d28f66a81f48bf394',
    messagingSenderId: '886098407421',
    projectId: 'imdr-de346',
    authDomain: 'imdr-de346.firebaseapp.com',
    storageBucket: 'imdr-de346.appspot.com',
    measurementId: 'G-FQKYKZV7HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-sQCmSKIdyamayCR9RVq3rAqn8DAJaSs',
    appId: '1:886098407421:android:f64cb3be73ef51338bf394',
    messagingSenderId: '886098407421',
    projectId: 'imdr-de346',
    storageBucket: 'imdr-de346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClq9kbjddyyDAEL_QY2TeietOYHz_Yw7Q',
    appId: '1:886098407421:ios:034dd30ecdc3f12f8bf394',
    messagingSenderId: '886098407421',
    projectId: 'imdr-de346',
    storageBucket: 'imdr-de346.appspot.com',
    iosBundleId: 'com.example.hackathonApp',
  );
}
